version: '3.8'

services:
  mega-sena-hacker:
    build: .
    container_name: mega-sena-hacker-app
    ports:
      - "5000:5000"
    environment:
      - DB_USER=${DB_USER:-alebrotto}
      - DB_PASSWORD=${DB_PASSWORD:-BrottoK@was0975}
      - DB_HOST=${DB_HOST:-utils_postgress}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-utils}
      - DB_SCHEMA=${DB_SCHEMA:-Mega-Sena-4}
      - PORT=5000
      - DEBUG=False
    restart: unless-stopped
    networks:
      - mega-sena-network

networks:
  mega-sena-network:
    driver: bridge
